name: Fetch YouTube Data

on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        
      - name: Install dependencies
        run: bun install
        
      - name: Fetch YouTube data
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ vars.CHANNEL_ID }}
          CWD: ${{ github.workspace }}
        run: bun run scripts/fetch-youtube-data.ts
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add public/data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "build: update YouTube data" && git push)
